alias dspace='bash /srv/dspace/bin/dspace'
alias task='ant -f /srv/dspace-src/dspace/target/dspace-installer/build.xml'
alias tomcat='$CATALINA_HOME/bin/catalina.sh'
alias copy_webapps='cp -R /srv/dspace/webapps/* /usr/local/tomcat/webapps/'
alias catalina.out='tail -f $CATALINA_HOME/logs/catalina.out'